### ISSUE TITLE
xgboost translation

### ISSUE THREAD

**Issue by edgararuiz** [tidymodels/tidypredict#40]
Look into adding xgboost translation

**Comment by JiaxiangBU** [comment]
I think there is a good source to solve the binary classification problem in the Xgboost Model. I test his code and use it in the production now.

Maybe the translated code is too long in sql (about 6000 lines), but in Hive it just costs 23 seconds in my recent experience.

**Comment by edgararuiz** [comment]
Ok @JiaxiangBU I'll take a look, thank you so much for these references.

**Comment by edgararuiz** [comment]
Fixed by #43
