### ISSUE TITLE
[Feature request] Add support for decision tree from the rpart package

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/tidypredict#46]
Classification And Regression Tree (CART) is a very popular model so I think it should be included in the supported model list of `tidypredict`.

At first it seems that an `rpart` model can be obtained by training a `randomForest` model with `ntrees`=1 and `mtry`=<number_of_predictors>; however, there is no way to prune the tree using cost-complexity pruning.

Even though in most cases, `rpart` is inferior to `randomForest` in terms of accuracy, there are still some circumstances (e.g., when the data set is big, or when the relationship between predictors and outcome is straightforward) where `rpart` is preferred.

**Comment by topepo** [comment]
This currently works for regression trees if you convert the model to a `party` object: 

``` r
library(rpart)
library(tidypredict)
library(partykit)
#> Loading required package: grid
#> Loading required package: libcoin
#> Loading required package: mvtnorm

mod <- rpart(mpg ~ ., data = mtcars)

mod_pk <- as.party(mod)

tidypredict_fit(mod_pk)
#> case_when(hp <= 192.5 & cyl <= 5 ~ 13.4142857142857, hp > 192.5 & 
#>     cyl <= 5 ~ 18.2642857142857, cyl > 5 ~ 26.6636363636364)
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

No classification tree implementation yet.
