### ISSUE TITLE
Feature Request: Add support for in-database goodness-of-fit computations

### ISSUE THREAD

**Issue by akgold** [tidymodels/tidypredict#55]
For example, if I pull down a sample of data, run a `glm`, it'd be awesome to be able to use the entire rest of my data as the test set, using `tidypredict::tidypredict_to_column()` and some currently nonexistent functionality to run AUC or R^2 on remaining data.

**Comment by topepo** [comment]
I think that's out of scope for `tidypredict`. We want to focus on getting the predictions. After that, other packages can be used (assuming I understand the request correctly)
