### ISSUE TITLE
[Feature request] approximate prediction using lookup table for gam and other models not returning explicit rules.

### ISSUE THREAD

**Issue by jacekkotowski** [tidymodels/tidypredict#60]
Accommodation for models that do not produce explicit rules intercepts and slopes like for mcgv::gam models by using a lookup table to generate approximate prediction. Example: https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/predict.gam.html and https://stats.stackexchange.com/questions/406566/using-gam-outside-statistical-modelling-software-in-datatabase-outside-r

**Comment by topepo** [comment]
That is difficult from a technical point of view since the analytic equations for splines would need to be embedded in the equation. I've love to have it but it is not on the the current roadmap.
