### ISSUE TITLE
Is it possible to conduct cost sensitive learning under Tidymodels framework?

### ISSUE THREAD

**Issue by mickeyang** [tidymodels/tidypredict#93]
Hi team,
I am having an unbalanced data set. I am using the rand_forest() interface for modelling but it turned out the sensitivity of the positive case was very poor. I understand the underlying engine "ranger" has an argument called "class.weight" which can be used to set up the cost matrix and for unbalanced learning. 

Is it possible to specify that argument in the rand_forest interface? Otherwise, any other approaches I can use to achieve my goal?
Please kindly advise.

Have a good day.

**Comment by juliasilge** [comment]
Hello there @mickeyang! 👋  It looks like this issue doesn't belong here on tidypredict, which is a package for running predictions inside of databases.

- For general "how to" questions and discussions about modeling and machine learning, we recommend [posting on RStudio Community](https://rstd.io/tidymodels-community).
- If you have imbalanced data, check out the [themis](https://themis.tidymodels.org/) package for preprocessing steps to deal with such data.
- If you are interested in a general cost metric within tidymodels, you might want [to check out our current work in this PR](https://github.com/tidymodels/yardstick/pull/196).

Good luck! 🙌

**Comment by mickeyang** [comment]
Thanks for your feedback.
Very helpful information.

Have a good day.


Warm regards,
Yi Yang


Let data bring us a better life.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
