### ISSUE TITLE
Re-licensing tidypredict 💫

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/tidypredict#95]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/tidypredict/graphs/contributors). 

@alyssafrazee, @Athospd, @bfgray3, @JiaxiangBU, @saadaslam, @tslumley, @washcycle, would you permit us to re-license tidypredict with the MIT license? If so, please comment "I agree" below.

* [x] [@alyssafrazee](https://github.com/tidymodels/tidypredict/commits?author=alyssafrazee)  
* [x] [@Athospd](https://github.com/tidymodels/tidypredict/commits?author=Athospd)  
* [x] [@bfgray3](https://github.com/tidymodels/tidypredict/commits?author=bfgray3)  
* [x] [@JiaxiangBU](https://github.com/tidymodels/tidypredict/commits?author=JiaxiangBU)  
* [x] [@saadaslam](https://github.com/tidymodels/tidypredict/commits?author=saadaslam)  
* [x] [@tslumley](https://github.com/tidymodels/tidypredict/commits?author=tslumley)  
* [x] [@washcycle](https://github.com/tidymodels/tidypredict/commits?author=washcycle)

**Comment by washcycle** [comment]
I agree

**Comment by saadaslam** [comment]
I agree.

**Comment by Athospd** [comment]
I agree.

**Comment by alyssafrazee** [comment]
I agree

**Comment by JiaxiangBU** [comment]
I agree.

**Comment by tslumley** [comment]
I agree

**Comment by bfgray3** [comment]
I agree

**Comment by juliasilge** [comment]
Thank you so much, all! 🙌
